### ISSUE TITLE
Bedarf-Signalisierung zu einem Zeitfenster

### ISSUE THREAD

**Issue by Tombra1889** [rg-engineering/ioBroker.semp#208]
Aktuell nutze die Anwendung SmartApplianceEnabler, ich habe dort aber Probleme mit mqtt und überlege ich auf ioBroker.semp zu wechseln. 

Im SmartApplianceEnabler gibt es die Funktion, dass ich ein Zeitfenster nur bei Bedarf aktivieren kann. Die beschriebe Funktion ermöglicht die Einplanung eines Geräts durch den Sunny-Home-Manager nur dann, wenn das Gerät wirklich einen Bedarf meldet. 

https://github.com/camueller/SmartApplianceEnabler/issues/384

**Comment by rg-engineering** [comment]
In Version 1.4.x baue ich einen Schalter ein:
![grafik](https://github.com/rg-engineering/ioBroker.semp/assets/8238668/910a0587-ae76-4b5d-ae0a-fffc3e24f58f)

Wenn dieser Datenpunt auf false gesetzt wird, wird der timeframe nicht für Energieanforderungen verwendet.

Alternativ kann man diese Option verwenden:
Hier wird zwar Energie vom SHM angefragt, wenn das Gerät sich aber nicht einschaltet, wenn der Einschaltbefehl kommt, wird die Energieanfrage abgebrochen und nicht weiter beim SHM angefragt:
![grafik](https://github.com/rg-engineering/ioBroker.semp/assets/8238668/15d9e12d-1c00-4158-80e7-2554d87d318e)

**Comment by rg-engineering** [comment]
@Tombra1889 konntest du das Verhalten hier schon mal testen?

**Comment by Tombra1889** [comment]
Leider scheint es noch nicht so ganz zu funktionieren:
<img width="754" alt="image" src="https://github.com/rg-engineering/ioBroker.semp/assets/60692414/f2092e55-90c2-45ec-956b-c761717038bf">

"Active" habe ich während des aktiven Zeitfensters auf false gestellt, aber leider erkenne ich noch keine Auswirkung im SunnyPortal.

**Comment by rg-engineering** [comment]
Kannst du bitte mal den output posten, den du im browser bekommst, wenn du
`http://192.168.xxx.xxx:9765/semp`
aufrufst.
Bitte dabei 192.168.xxx.xxx durch die IP des Systems ersetzen, wo dein ioBroker - Semp-Adapter läuft.

Vielleicht in beiden Fällen: mit Active = true und mit Active = false...

**Comment by Tombra1889** [comment]
Active = true: 
`F-########-000000000001-00 Luftentfeuchter AirConditioning 70 TROTEC 420 1200 300 Measurement false true true F-########-000000000001-00 true Off 0 0 60 1 F-########-000000000001-00 0 5644 0 36000`
Active = false:
`F-########-000000000001-00 Luftentfeuchter AirConditioning 70 TROTEC 420 1200 300 Measurement false true true F-########-000000000001-00 true Off 0 0 60`

Es passiert anscheinend schon etwas.

**Comment by Trunks1982** [comment]
Das Zeitfenster schliessen kann schonmal 10-15min dauern.

**Comment by Tombra1889** [comment]
Hat funktioniert! Ich habe einfach nicht lange genug gewartet.
