### ISSUE TITLE
sentry: Cannot read properties of undefined (reading 'setOnOff')

### ISSUE THREAD

**Issue by rg-engineering** [rg-engineering/ioBroker.semp#22]
TypeError Gateway.setOnOffDevice(iobroker.semp.lib.semp:Gateway)
Cannot read properties of undefined (reading 'setOnOff')

**Comment by Trunks1982** [comment]
Hi adapter stürzt immer ab.lässt sich nicht mehr starten nach dem update auf 0.0.6

**Comment by rg-engineering** [comment]
should be fixed with 0.0.7
