### ISSUE TITLE
Gerät nicht im Sunny Portal zu finden?

### ISSUE THREAD

**Issue by gyroslav** [rg-engineering/ioBroker.semp#245]
Hallo, 
ich brauche wohl noch Hilfe beim Einrichten. 
Ich will meine Wallbox als "Verbraucher" im Portal sehen können. SHM soll nichts schalten können. 

Hier die Konfig:
![grafik](https://github.com/rg-engineering/ioBroker.semp/assets/79666110/f90fb4ab-d2b0-4125-9e14-6cd7d0f09ef3)

![grafik](https://github.com/rg-engineering/ioBroker.semp/assets/79666110/5042bf69-518a-44de-a7a0-e1c619a2fd93)

![grafik](https://github.com/rg-engineering/ioBroker.semp/assets/79666110/7ffaeeba-7247-406b-afda-be17efe5c172)

![grafik](https://github.com/rg-engineering/ioBroker.semp/assets/79666110/e5351e15-120b-42cd-96d1-3466463ded2e)

Device ist da und zählt fleißig mit:
![grafik](https://github.com/rg-engineering/ioBroker.semp/assets/79666110/ab9027b3-5730-4870-a5e1-bfb128b1cc44)

Das SEMP-Gateway wurde vom Portal wohl auch gefunden:
![grafik](https://github.com/rg-engineering/ioBroker.semp/assets/79666110/7984b1e4-5865-4a98-ad9d-552677386c4d)

Aber die Wallbox selber sehe ich nirgendwo als Verbraucher. 
Was mache ich falsch? 

Schöne Grüße
Eugen

**Comment by rg-engineering** [comment]
Im Portal sollte ein neues Gerät auftauchen, wie hier beschrieben:
https://forum.iobroker.net/topic/58606/adapter-sma-semp/136

Im ioBroker log erscheint keine Warnung?
