### ISSUE TITLE
Please implement save function in your admin/index.html

### ISSUE THREAD

**Issue by Eldron81** [rg-engineering/ioBroker.semp#25]
**Describe the bug**  
Trying to save any config Popup comes with "Please implement save function in your admin/index.html".

**Screenshots & Logfiles**  
Screen attached

**Versions:**  
 - Adapter version: 0.1.0
 - JS-Controller version: 4.0.24
 - Node version: v16.19.0
 - Operating system: linux

![screen](https://user-images.githubusercontent.com/98782407/212738911-70c92e87-3db1-49a4-be51-a13360a0f941.JPG)

**Comment by rg-engineering** [comment]
does it appear when you open the admin page (like described here https://forum.iobroker.net/topic/58606/adapter-sma-semp/90) or does it appear really when you press save button on the upper right corner?

**Comment by Eldron81** [comment]
With opening the admin page - as described. I'll double check more with the forum.

I now deleted 0.1.0 and went back to 0.0.5 via NPM, error gone. I'll continue testing...
