### ISSUE TITLE
Gerät wird trotz "waiting" mit dem Verbrauchsschätzwert im Sunnyportal angezeigt

### ISSUE THREAD

**Issue by Tombra1889** [rg-engineering/ioBroker.semp#250]
**Describe wanted Enhancement !**  
Das Gerät ist nur mit dem Verbrauchsschätzwert konfiguriert. Dieser wird trotz des Status "waiting" als aktueller Verbrauch im Sunnyportal angezeigt, obwohl das Gerät aus ist.

<img width="1760" alt="image" src="https://github.com/rg-engineering/ioBroker.semp/assets/60692414/f525db28-099c-409a-89be-ea704806d810">

<img width="739" alt="image" src="https://github.com/rg-engineering/ioBroker.semp/assets/60692414/2f49783b-d8d6-406d-9b5f-f3bb3e40c67b">

**Comment by rg-engineering** [comment]
wie wird denn der Status (an/aus) erkannt?
![grafik](https://github.com/rg-engineering/ioBroker.semp/assets/8238668/49ea68d5-f28c-4192-aaae-d434ce0ce2a4)

**Comment by Tombra1889** [comment]
<img width="928" alt="image" src="https://github.com/rg-engineering/ioBroker.semp/assets/60692414/8b3d6168-84c0-4b69-8986-44b53f2bcf86">
so sieht das Objekt aus:
<img width="1735" alt="image" src="https://github.com/rg-engineering/ioBroker.semp/assets/60692414/6dcac491-11bb-4449-aa6e-15d6166015fa">
Die Steuerung funktioniert auch, nur werden die "25 Watt" auch angezeigt, wenn das Gerät aus ist. Bei einem anderen Gerät, mit richtigem Leistungswert (ohne Schätzwert) ist dieses Verhalten ja auch korrekt. Aber bei einem Schätzwert, würde ich 0 oder den Minimalwert bevorzugen.

**Comment by rg-engineering** [comment]
Wenn der Geräte-Status richtig erkannt wird, sollte bei eingeschaltetem Gerät die maximale Leistung (wie konfiguriert) und bei ausgeschaltetem Gerät 0W als Leistung übertragen werden.

Kannst du ein debug log erzeugen, damit ich sehen kann, warum das nicht funktioniert?

**Comment by Tombra1889** [comment]
Wie erstelle ich das Log genau?
Bei anderen Geräten mit Messung funktioniert es korrekt. Nur bei den Geräten ohne Messung nicht.

**Comment by rg-engineering** [comment]
Ich schaue mir das nochmal an....

**Comment by rg-engineering** [comment]
@Tombra1889  Versuche es mal mit der 1.4.5 ...

**Comment by Tombra1889** [comment]
Vielen Dank, mit der Version funktioniert es korrekt!
