### ISSUE TITLE
Exception on Starting SMA SEMP-Gateway

### ISSUE THREAD

**Issue by Savari-dev** [rg-engineering/ioBroker.semp#319]
Hi all,

I have installed and configured the SMA SEMP-Gateway V 1.4.6. in iobroker. Unfortunately during start of the instance an exception 
"exception in onReady [TypeError: Missing parameter name at 1: https://git.new/pathToRegexpError]" is thrown.
Nevertheless the instance seems to be started, the status becomes green. Unfortunately the SEMP-Adapter does not show up in SMA Portal.
[SMA SEMP-Gateway Exception.txt](https://github.com/user-attachments/files/17026661/SMA.SEMP-Gateway.Exception.txt)
See attached the debug-informations.

I have tested different params for the adapter but was not able to get rid of the exception. Maybe you have an idea:-)

Best regards,
Dörte

**Comment by rg-engineering** [comment]
siehe hier: https://github.com/rg-engineering/ioBroker.semp/issues/314

**Comment by Savari-dev** [comment]
Lieben Dank, mit der 1.4.7 tritt die Exception nicht mehr auf und der Adapter ist im Sunny Portal sichtbar :-)
