### ISSUE TITLE
current power is not shown in SunnyPortal 

### ISSUE THREAD

**Issue by rg-engineering** [rg-engineering/ioBroker.semp#5]
see https://github.com/ioBroker/AdapterRequests/issues/689

[Trunks1982](https://github.com/Trunks1982)  and [Tagiwara](https://github.com/Tagiwara) report that no power values are shown in SunnyPortal

**Comment by rg-engineering** [comment]
[Trunks1982](https://github.com/Trunks1982), [Tagiwara](https://github.com/Tagiwara)  habe den Status check basierend auf aktueller Leistung mal eingebaut...

**Comment by Trunks1982** [comment]
Hab den adapter mal upgedatet aber daten kommen noch nicht rein.Dein on schalter ist aufjedenfall zu sehn im log

**Comment by rg-engineering** [comment]
ich kann das Problem nun auch hier nachvollziehen: nachdem ich den Adapter auf einem weiteren System installiert habe, kommen von dort auch keine Daten. Vom ersten Testsystem und vom SAE kommen weiterhin Daten im Portal an. Das hat anscheinend auch nichts mit dem Status zu tun: der SAE schickt Status=off, trotzdem wird die aktuelle Leistung im Portal angezeigt. Ich vergleiche nun schon zum x-ten mal die xml-Daten zwischen den drei Systemen und sehe einfach keinen Unterschied...

**Comment by Trunks1982** [comment]
Komisch.Am Sae haste auch deine“ gleiches Gerät drin?

**Comment by rg-engineering** [comment]
ich denke, das ist keine Problem der Kommunikation zwischen Adapter und HomeManager, sondern ein Problem im Adapter. Ich sehe aktuell unterschiedliches Verhalten zwischen meinem Testaufbau mit script-basierter Quelle der Power und "echten" HM-Mess-Steckdosen. Du hast auch eine echte Steckdose verwendet? Ändert sich die Leistung regelmässig?
Außerdem:
* hat dein Adapter beim Gerät eine ID im Format "F-11223344-112233445566-00" angelegt? wenn nicht, bitte die BaseID und die Geräte ID im admin vom adapter löschen, speichern und admin neu öffnen. Dann sollte die Base-ID vorbelegt sein. Wenn du dann die Power-OID nochmal auswählst, sollte auch die Geräte-ID richtig gestzt sein
* hat der Adapter die UUID im admin automatisch richtig vergeben?
* hast du in der Geräte-Konfiguration im admin vom Adapter für das Gerät Name, max.Power, Verkäufer / vendor und Seriennummer ausgefüllt?

**Comment by Trunks1982** [comment]
![Bildschirmfoto 2022-09-02 um 13 40 04](https://user-images.githubusercontent.com/62701386/188131945-b1b54ba4-a3f6-4f73-8501-0620b30d6f49.png)
ich hab zwei verschiedene Geräte angelegt.Das zweite Gerät läuft mit dem Datenpunkt so im SAE.Also normal müsste das so laufen von den Einstellungen her.

**Comment by rg-engineering** [comment]
mindestens das zweite Gerät sollte Daten liefern, wenn sie sich ändern. Beim ersten fehlt "vendor", wenn ich das hier nicht ausgefüllt hatte, wurden die Daten auch nicht übertragen...
In meinem zweiten System werden nun auch Daten ins Portal übertragen, da war das Problem, dass sich die Leistungsdaten nicht geändert haben und damit der Datensatz leer war. Das habe ich im Adapter jetzt geändert: beim Start des Adapter werden die aktuellen Daten geholt. Damit ist der Datensatz nicht leer...

**Comment by Trunks1982** [comment]
zweite Gerät liefert immer Daten aber kommt trotzdem nichts im portal an.

**Comment by Trunks1982** [comment]
![Bildschirmfoto 2022-09-02 um 13 57 31](https://user-images.githubusercontent.com/62701386/188137962-6e431053-73d4-4f38-aae2-3fd00bc71dd4.png)

**Comment by rg-engineering** [comment]
ruf mal im browser http://192.168.3.43:9765/semp (natürlich mit deiner ioBroker-IP) auf. Wahrscheinlich löst der browser dann die xml auf, deshalb dann noch rechte Maustaste und "Seitenquelltext anzeigen" aufrufen. Dann müsstest du die xml-Daten sehen, die der HomeManager bekommt. Kannst du mir das zukommen lassen? gern auch per email (info@rg-engineering.eu).

Das sieht so ähnlich aus:


![grafik](https://user-images.githubusercontent.com/8238668/188142176-0d17aea6-c280-4dd8-a034-f9ff823c75cf.png)

**Comment by Trunks1982** [comment]
Hab jetzt auch mal mit dem sä vergleichen sieht eigentlich alles gleich aus.

**Comment by Trunks1982** [comment]
Ah hab jetzt nochmal die base id usw geändert jetzt kommen werte an😉

**Comment by rg-engineering** [comment]
ich habe den Adapter jetzt auch bei mir im live-System installiert, WaMa und Trockner - Werte kamen direkt an...

Das heisst aber, dass man einmal angelegte Geräte nicht ändern kann. Geht das im SAE?

**Comment by Trunks1982** [comment]
Was meinst mit ändern?solen wir nicht über telegram schreiben glaub einfacher oder🤣

**Comment by rg-engineering** [comment]
> sollen wir nicht über telegram schreiben glaub einfacher oder

ja, gern

> Was meinst mit ändern?

die Geräte-Einstellung z.Bsp. Typ, MaxPower, Seriennummer, Hersteller usw. Ich befürchte, ein einmal angelegtes Gerät lässt sich im Portal nicht mehr ändern. Änderungen werden nur übernommen, wenn man die ID ändert, also das Gerät neu anlegt...

**Comment by Trunks1982** [comment]
Hab dir ne email geschrieben.
