### ISSUE TITLE
Gerät wird bei Erreichen der max. Energie nicht ausgeschaltet

### ISSUE THREAD

**Issue by rg-engineering** [rg-engineering/ioBroker.semp#50]
Gerät sollte bei Erreichen der max. Laufzeit oder spätestens am Ende der max. möglichen Einschaltzeit ausgeschaltet werden.
Manchmal ist das nicht der Fall und das Gerät bleibt an

**Comment by Trunks1982** [comment]
Mhm ok.Mit freundlichen GrüßenChristoph Badurczyk Am 18.05.2023 um 18:33 schrieb rg-engineering ***@***.***>:﻿
Gerät sollte bei Erreichen der max. Laufzeit oder spätestens am Ende der max. möglichen Einschaltzeit ausgeschaltet werden.
Manchmal ist das nicht der Fall und das Gerät bleibt an

**Comment by rg-engineering** [comment]
sollte jetzt mit der 1.2.0 behoben sein...

**Comment by Trunks1982** [comment]
Ok werde es testen.Mit freundlichen GrüßenChristoph Badurczyk Am 29.05.2023 um 18:04 schrieb rg-engineering ***@***.***>:﻿
sollte jetzt mit der 1.2.0 behoben sein...
