### ISSUE TITLE
Please correct npm maintainers configuration.

### ISSUE THREAD

**Issue by GermanBluefox** [rg-engineering/ioBroker.semp#59]
## ioBroker adapter checker for npm access

Access right check for adapter semp returned the following issue:

Bluefox was not found in the collaborators on NPM!.
Please execute in adapter directory: "npm owner add bluefox iobroker.semp"

Current maintainers are 
    rg-engineering <info@rg-engineering.eu>

Please fix the above error as soon as possible.
All adapters listed at ioBroker repositories must have 'bluefox' added as maintainer.

Future version updates at the repositories will be suspended until this problem is fixed.

**Comment by rg-engineering** [comment]
```
E:\Software\ioBroker\ioBroker.semp>npm owner add bluefox iobroker.semp
npm notice INFO: User bluefox invited to package iobroker.semp successfully.
+ bluefox (iobroker.semp)

```

@GermanBluefox  done

**Comment by mcm1957** [comment]
access now ok.
Issue can be closed.
THANKs
