### ISSUE TITLE
device base-ID, UUID and ip-address  not calculated automatically 

### ISSUE THREAD

**Issue by rg-engineering** [rg-engineering/ioBroker.semp#6]
device dase id should be calculated automatically after installation.
At the moment it's just "0" after installation. If it's deleted and admin is restarted then it is calculated okay...
the same for UUID and ip-address  after first installation...

**Comment by TeraX** [comment]
Hi,

for me it's not clear which IP Address needs to be entered.
Is it from the iobroker host or from the SMA HomeManager?

Also the UUID will not filled in with the described work around in the start thread.
Maybe this is related to issue #8

**Comment by rg-engineering** [comment]
we need to use IP from ioBroker where the adapter runs.
The idea is that IP and UUID should be filled in automatically when adapter is called the first time. I overworked it already a bit but this change is not available here in github. will push it soon...
