### ISSUE TITLE
Data not received/handled by SHM: check MaxPowerConsumption

### ISSUE THREAD

**Issue by kesch001de** [rg-engineering/ioBroker.semp#74]
Hi all, 

Specs: 
Plattform = linux
Betriebssystem = linux
Node.js = v18.16.1
js-controller: 4.0.24

The adapter worked fine already and data are transmitted to the SHM / SunnyPortal properly.
Since 1 week and update to node.js 18.16.1 the SHM seams not to be connected anymore.
Not really sure, if the update is related to the issue.
Today, manual update to latest adapter version done as well - no change.

Snapshot logs:
![image](https://github.com/rg-engineering/ioBroker.semp/assets/68777942/506c0fc9-0e65-49ad-9ab4-385e27d9ee6e)

Logs look good as well:
[log_20230710.csv](https://github.com/rg-engineering/ioBroker.semp/files/12004053/log_20230710.csv)
Data are generated / Adapter is "green".

Within the SunnyPortal, the devices are initially configured and data are received in the past.
![image](https://github.com/rg-engineering/ioBroker.semp/assets/68777942/be89d2cc-eb3b-4341-8adc-03ad791ef249)

Adding new devices works in the adapter, but they are not shown in the SunnyPortal.

The permanent updates from the adapter are running as well - checking debug logs.
![image](https://github.com/rg-engineering/ioBroker.semp/assets/68777942/d520eed7-4165-40d2-81d5-33e4d631b784)

Pinging the SHM works.
![image](https://github.com/rg-engineering/ioBroker.semp/assets/68777942/8b4d1f72-a3d4-4c30-9c72-6f07c1214665)

In the SunnyPortal logs, i can see some entries.
![image](https://github.com/rg-engineering/ioBroker.semp/assets/68777942/8e1552ef-40e3-490c-b8da-fe95759fabfc)

Any ideas, what else I can check and what might be the issue.

Thanks for your support, much appreciated!!

Best, 
Kevin

**Comment by rg-engineering** [comment]
you know that new devices first appear in sunny portal and you must configure them first?

![grafik](https://github.com/rg-engineering/ioBroker.semp/assets/8238668/9299e5be-5e45-48c0-94e8-c1729b9b4264)

**Comment by rg-engineering** [comment]
and from log side I miss something like that:


```
semp.0 | 2023-07-14 15:15:56.179 | debug | response sent
semp.0 | 2023-07-14 15:15:56.177 | debug | response  xml <?xml version="1.0" encoding="utf-8"?><Device2EM  xmlns="http://www.sma.de/communication/schema/SEMP/v1">     <DeviceInfo>        <Identification>             <DeviceId>F-53088660-000000000002-00</DeviceId>             <DeviceName>Heizung</DeviceName>             <DeviceType>Heater</DeviceType>             <DeviceSerial>ABCDEFGE</DeviceSerial>             <DeviceVendor>noName</DeviceVendor>         </Identification>        <Characteristics>             <MaxPowerConsumption>3000</MaxPowerConsumption>         </Characteristics>        <Capabilities>             <CurrentPower>                 <Method>Measurement</Method>             </CurrentPower>            <Timestamps>                 <AbsoluteTimestamps>false</AbsoluteTimestamps>             </Timestamps>            <Interruptions>                 <InterruptionsAllowed>false</InterruptionsAllowed>             </Interruptions>            <Requests>                 <OptionalEnergy>true</OptionalEnergy>             </Requests>        </Capabilities>    </DeviceInfo>     <DeviceStatus>         <DeviceId>F-53088660-000000000002-00</DeviceId>         <EMSignalsAccepted>true</EMSignalsAccepted>         <Status>Off</Status>        <PowerConsumption>             <PowerInfo>                 <AveragePower>0</AveragePower>                 <Timestamp>0</Timestamp>                 <AveragingInterval>60</AveragingInterval>             </PowerInfo>        </PowerConsumption>     </DeviceStatus>    <PlanningRequest>         <Timeframe>            <TimeframeId>2</TimeframeId>             <DeviceId>F-53088660-000000000002-00</DeviceId>             <EarliestStart>0</EarliestStart>             <LatestEnd>9845</LatestEnd>             <MinRunningTime>1800</MinRunningTime>             <MaxRunningTime>5400</MaxRunningTime>         </Timeframe>    </PlanningRequest></Device2EM>
semp.0 | 2023-07-14 15:15:56.176 | debug | write  to csv [{"Time":"14.7.2023,  15:15:56","DeviceId":"F-53088660-000000000002-00","DeviceName":"Heizung","Status":"Off","AveragePower":0,"TimeFrameID":"2","EarliestStart":0,"LatestEnd":9845,"MinRunningTime":1800,"MaxRunningTime":5400,"MinEnergy":-1,"MaxEnergy":-1}]
semp.0 | 2023-07-14 15:15:56.175 | debug | got  all devices  [{"deviceInfo":{"Identification":{"DeviceId":"F-53088660-000000000002-00","DeviceName":"Heizung","DeviceType":"Heater","DeviceSerial":"ABCDEFGE","DeviceVendor":"noName"},"Characteristics":{"MaxPowerConsumption":"3000"},"Capabilities":{"CurrentPower":{"Method":"Measurement"},"Timestamps":{"AbsoluteTimestamps":false},"Interruptions":{"InterruptionsAllowed":false},"Requests":{"OptionalEnergy":true}}},"deviceStatus":{"DeviceId":"F-53088660-000000000002-00","EMSignalsAccepted":true,"Status":"Off","PowerConsumption":{"PowerInfo":[{"AveragePower":0,"Timestamp":0,"AveragingInterval":60}]}},"planningRequest":{"Timeframe":[{"TimeframeId":"2","DeviceId":"F-53088660-000000000002-00","EarliestStart":0,"LatestEnd":9845,"MinRunningTime":1800,"MaxRunningTime":5400}]}}]
```

That means that your SHM does not ask for status update of devices ever 60 seconds

**Comment by kesch001de** [comment]
Hi @rg-engineering
Thanks for checking the issue.
Yes, i am aware, that all devices must be configured before in SunnyPortal. 
That was done in the past while all was working initally.

Kindly find the complete debug logs following.
[iobroker.2023-07-15.log](https://github.com/rg-engineering/ioBroker.semp/files/12061192/iobroker.2023-07-15.log)

Please let me know in case other logs/details are needed.

Thanks, 
Kevin

**Comment by rg-engineering** [comment]
Hi @kesch001de for me the log looks pretty well. 
I would try to change DeviceId. At this moment you use "F-18100480-0000000000zz-00". In worst case someboday else use the same ID now. So change the part "18100480" to anything else and try again...

**Comment by kesch001de** [comment]
Hi @rg-engineering, 
After re-installing the adapter, deletion of all devices in SunnyPortal, changing the ID, adding just one new device -  unfortunately no changes. There are no new devices discovered in SunnyPortal.

Logs are attached - 
[iobroker.2023-07-30.log](https://github.com/rg-engineering/ioBroker.semp/files/12208846/iobroker.2023-07-30.log)

I can see some kind of communication from the SEMP GW, but no further log entries anymore.
![image](https://github.com/rg-engineering/ioBroker.semp/assets/68777942/cfd79956-ea6e-41da-b0a8-3b0cc647b016)

Thanks, 
Kevin

**Comment by rg-engineering** [comment]
something is strange now in log:
1) SHM requests description many times and very often
2) SHM requests device status too often. Normally we see one rquest per minute, in your case I see many requests per second

Could you please check logs from SHM? 
Here you can find a description how to do:
https://github.com/rg-engineering/ioBroker.semp/blob/master/docu/connection_assist/connection_assist_de.md

**Comment by kesch001de** [comment]
hi @rg-engineering, 
thanks for your further investigations.
pls find the requested logs attached.
[Sunny Home Manager--1288016617-20230730.zip](https://github.com/rg-engineering/ioBroker.semp/files/12209182/Sunny.Home.Manager--1288016617-20230730.zip)

**Comment by rg-engineering** [comment]
The SHM log shows an communication error

> [2023-07-30T12:46:55] SEMP(Info): SEMP update
> [2023-07-30T12:46:55] SEMP(Info): Request all information from gateway 'SSDP:4f5314ad-f0ee-461e-9973-5721fd41ed7c'
> [2023-07-30T12:46:55] SEMP(Info): CommunicatorAdapterHTTP::send: could not deserialize response
> [2023-07-30T12:46:55] SEMP(Info): Communicator::send: could not send buffer

Right now I've no clue why...

**Comment by rg-engineering** [comment]
can you try to add a "MaxPowerConsumption"?
![grafik](https://github.com/rg-engineering/ioBroker.semp/assets/8238668/7ad8b544-eb5e-425e-9494-600d927b210a)

**Comment by kesch001de** [comment]
yesssssss ... that was the issue.

all looks good and normal now.
![image](https://github.com/rg-engineering/ioBroker.semp/assets/68777942/90e097d3-8a5b-4348-8aff-fabd5ccb9c98)

Maybe, it would be worth to set the field as madatory input value in one of the next updates.
Just to avoid the user missconfig.

Many thanks for the support!!!!!!
Much appreciated
