### ISSUE TITLE
support of URL for 3 phase Enabler with wallboxes

### ISSUE THREAD

**Issue by rg-engineering** [rg-engineering/ioBroker.semp#81]
should be like the other wallbox setiings in the list

**Comment by Trunks1982** [comment]
Hi kannst du die Zeit für die 3phasen Umschaltung im Adapter Variable machen?
Ist ja glaub fest auf 3min eingestellt?!
Und noch ne Frage wenn in den 3min zb von 3phasig auf 1phasig umgestellt werden soll aber wieder genug Sonne da ist um 3phasig weiter zu laden fängt der Time dann wieder von vorne an oder sind die 3min fest das er aufjedenfall umschaltet?

**Comment by rg-engineering** [comment]
Zeit kann ich einstellbar machen.
Den Ablauf kannst du im debug log verfolgen:

wenn aktuelle Power größer als das limit, wird ein Timer gestartet (log "start 3phase charging start timer").
Falls zu diesem Zeitpunkt der Stop-Timer noch läuft, wird der abgebrochen (log "cancel 3phase charging stop timer")

d.h. wenn während des Stop-Timers (von 3 phasig auf 1 phasig) wieder genügend Energie vorhanden ist, wird zwar der Start-Timer neu gestartet, da aber noch 3 phasig geladen wird, sollte es keine kurzzeitige Umschaltung auf 1 phasig geben. 
Was aber hier mit hineinspielt ist ja die Verzögerung vom SHM, da der ja nur einmal pro Minute aktualisiert. Welche Auswirkung das auf das timing hat, erschliesst sich mir im Moment noch nicht...

**Comment by Trunks1982** [comment]
Ok.Was ich mich auch die ganze Zeit Frage ob zb das original wenn 1phasig geladen im Portal bei Leistungsanzeige zb nur 3800w angezeigt wird.Ich meine ich hätte das bei evcc zb gesehn.Der Wert ist aufjedenfall änderbar ohne das das Gerät neu erstellt werden muss.

**Comment by rg-engineering** [comment]
@Trunks1982 gibt es zwei verschiedene URL für aktivieren und deaktivieren des 3Phasen-Ladens, oder ist das eine URL mit Parameter?

**Comment by Trunks1982** [comment]
Bei dem go e ist das eine URL mit parameter 1 und 2.

**Comment by rg-engineering** [comment]
> Der Wert ist aufjedenfall änderbar ohne das das Gerät neu erstellt werden muss.

Welchen Wert möchtest du ändern? 

> Bei dem go e ist das eine URL mit parameter 1 und 2.

dann muss ich aber trotzdem zwei URL inkl. Paramter konfigurierbar machen...

**Comment by Trunks1982** [comment]
Den Leistungswert also 1phasig bei einer 22kw zb 7380w anstatt immer 22000w.Ich frage mich nur ob das bei der Originalen geändert wird wenn die auf 1phasig läuft

**Comment by Trunks1982** [comment]
Ah ok fix wusste ich nicht.Dachte es werden die angegeben Schwellwerte benutzt wie du oben beschrieben hast.Macht aufjedenfall sinn.

**Comment by Trunks1982** [comment]
![Bildschirmfoto 2023-08-22 um 09 05 07](https://github.com/rg-engineering/ioBroker.semp/assets/62701386/adfed5ee-a59e-40ff-8be2-bc3b6f23d95e)
![Bildschirmfoto 2023-08-22 um 09 06 04](https://github.com/rg-engineering/ioBroker.semp/assets/62701386/7e64dc64-14b1-419c-8e69-928dbfffb248)

da sind leider noch Fehler drin.

**Comment by rg-engineering** [comment]
@Trunks1982 habs noch weiter angepasst.

Aber: du musst den Parameter (2 oder 1) mit in die URL nehmen. Im Falle einer URL ignoriere ich alle angegebenen zusätzlichen Parameter. In der aktuellen Version überschreibe ich den Wert mit "not used"...

**Comment by Trunks1982** [comment]
Ok ich teste.

**Comment by Trunks1982** [comment]
Die Fehlermeldung kommt wenn ich die unten einstellte url nehme.Schaltet also nicht um.

![Bildschirmfoto 2023-08-27 um 14 34 28](https://github.com/rg-engineering/ioBroker.semp/assets/62701386/f74278c0-0c59-4549-beb7-f2a0e49ca7a9)
![Bildschirmfoto 2023-08-27 um 14 34 54](https://github.com/rg-engineering/ioBroker.semp/assets/62701386/fefc3f87-a5e2-492b-bf9b-97342d03b512)

**Comment by Trunks1982** [comment]
Neuste Version gerade getestet scheint zu funktionieren. Top

**Comment by rg-engineering** [comment]
> Hast du jetzt nur nen Warn Hinweis zugefügt oder muss man 4600 eingeben?

ist nur eine Warnung, hat keine weiteren Folgen...

> Fast Charging schaltet aber nicht direkt auf 3 phasig oder?

hier wird auch erst das delay abgewartet...

**Comment by Trunks1982** [comment]
> > Hast du jetzt nur nen Warn Hinweis zugefügt oder muss man 4600 eingeben?
> 
> ist nur eine Warnung, hat keine weiteren Folgen...
> 
> > Fast Charging schaltet aber nicht direkt auf 3 phasig oder?
> 
> hier wird auch erst das delay abgewartet...

Ok.

**Comment by Trunks1982** [comment]
Hi diese Fehlermeldung kommt noch ob wohl Phasenumschaltung funktioniert.
![Bildschirmfoto 2023-09-06 um 14 04 46](https://github.com/rg-engineering/ioBroker.semp/assets/62701386/a2fcd0df-23dd-4708-b525-415bd93a1c8d)

Konfig:
![Bildschirmfoto 2023-09-06 um 14 05 22](https://github.com/rg-engineering/ioBroker.semp/assets/62701386/a135365b-b9d0-4849-8595-e4813f64ff6e)

**Comment by rg-engineering** [comment]
sollte mit der 1.3.8 nun behoben sein
